language: bash
sudo: required
dist: trusty

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install -y -q libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1 curl screen tar wget

install:
  - sudo wget https://raw.githubusercontent.com/crazy-max/csgo-server-launcher/master/csgo-server-launcher.sh -O /etc/init.d/csgo-server-launcher --no-check-certificate
  - sudo chmod +x /etc/init.d/csgo-server-launcher
  - sudo update-rc.d csgo-server-launcher defaults
  - sudo mkdir /etc/csgo-server-launcher
  - sudo wget https://raw.githubusercontent.com/crazy-max/csgo-server-launcher/master/csgo-server-launcher.conf -O /etc/csgo-server-launcher/csgo-server-launcher.conf --no-check-certificate

before_script:
  - export IP_ADDRESS=`dig +short myip.opendns.com @resolver1.opendns.com`
  - sudo mkdir /var/steamcmd
  - sudo chown -R $USER. /var/steamcmd/
  - sudo sed "s/USER=\"steam\"/USER=\"$USER\"/" -i /etc/csgo-server-launcher/csgo-server-launcher.conf
  - sudo sed "s/IP=\"198.51.100.0\"/IP=\"$IP_ADDRESS\"/" -i /etc/csgo-server-launcher/csgo-server-launcher.conf
  - sudo sed "s/PARAM_START=\"-game/PARAM_START=\"-debug -game/" -i /etc/csgo-server-launcher/csgo-server-launcher.conf
  - sudo cat /etc/csgo-server-launcher/csgo-server-launcher.conf

script:
  - service csgo-server-launcher create
  - service csgo-server-launcher start
  - journalctl --unit=csgo-server-launcher | tail -100
  - tail -f /var/steamcmd/games/csgo/screenlog.* & P=$! ; sleep 30 ; kill -9 $P
  - service csgo-server-launcher stop
